# Generated by Django 4.1 on 2022-09-15 07:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Districts",
            fields=[
                ("gid", models.AutoField(primary_key=True, serialize=False)),
                ("layer", models.CharField(blank=True, max_length=17, null=True)),
                (
                    "area",
                    models.DecimalField(
                        blank=True, decimal_places=45535, max_digits=65535, null=True
                    ),
                ),
                (
                    "perimeter",
                    models.DecimalField(
                        blank=True, decimal_places=45535, max_digits=65535, null=True
                    ),
                ),
                ("indiadpoly", models.IntegerField(blank=True, null=True)),
                ("indiadpo_1", models.IntegerField(blank=True, null=True)),
                ("dist", models.CharField(blank=True, max_length=254, null=True)),
                ("cnt_dist", models.IntegerField(blank=True, null=True)),
                (
                    "sum_area",
                    models.DecimalField(
                        blank=True, decimal_places=45535, max_digits=65535, null=True
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                ("symbol", models.SmallIntegerField(blank=True, null=True)),
                (
                    "shape_leng",
                    models.DecimalField(
                        blank=True, decimal_places=45535, max_digits=65535, null=True
                    ),
                ),
                (
                    "shape_area",
                    models.DecimalField(
                        blank=True, decimal_places=45535, max_digits=65535, null=True
                    ),
                ),
                ("area_1", models.SmallIntegerField(blank=True, null=True)),
                ("area_12", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "db_table": "districts",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="States",
            fields=[
                ("gid", models.AutoField(primary_key=True, serialize=False)),
                ("layer", models.CharField(blank=True, max_length=17, null=True)),
                (
                    "area",
                    models.DecimalField(
                        blank=True, decimal_places=45535, max_digits=65535, null=True
                    ),
                ),
                (
                    "perimeter",
                    models.DecimalField(
                        blank=True, decimal_places=45535, max_digits=65535, null=True
                    ),
                ),
                (
                    "indiasln_field",
                    models.IntegerField(blank=True, db_column="indiasln_", null=True),
                ),
                ("indiasln_i", models.IntegerField(blank=True, null=True)),
                ("state", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "shape_leng",
                    models.DecimalField(
                        blank=True, decimal_places=45535, max_digits=65535, null=True
                    ),
                ),
                (
                    "shape_area",
                    models.DecimalField(
                        blank=True, decimal_places=45535, max_digits=65535, null=True
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "db_table": "states",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tahesil",
            fields=[
                ("gid", models.AutoField(primary_key=True, serialize=False)),
                ("id_0", models.FloatField(blank=True, null=True)),
                ("iso", models.CharField(blank=True, max_length=3, null=True)),
                ("name_0", models.CharField(blank=True, max_length=75, null=True)),
                ("id_1", models.FloatField(blank=True, null=True)),
                ("name_1", models.CharField(blank=True, max_length=75, null=True)),
                ("id_2", models.FloatField(blank=True, null=True)),
                ("name_2", models.CharField(blank=True, max_length=75, null=True)),
                ("id_3", models.FloatField(blank=True, null=True)),
                ("name_3", models.CharField(blank=True, max_length=75, null=True)),
                ("ccn_3", models.FloatField(blank=True, null=True)),
                ("cca_3", models.CharField(blank=True, max_length=15, null=True)),
                ("type_3", models.CharField(blank=True, max_length=50, null=True)),
                ("engtype_3", models.CharField(blank=True, max_length=50, null=True)),
                ("nl_name_3", models.CharField(blank=True, max_length=75, null=True)),
                ("varname_3", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=0
                    ),
                ),
            ],
            options={
                "db_table": "tahesil",
                "managed": False,
            },
        ),
    ]
